services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        APP_VERSION: ${VERSION} # bakes into image
    environment:
      NODE_ENV: development
      APP_VERSION: ${VERSION} # runtime env
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./extension:/extension:ro
    ports:
      - "3004:3004"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        APP_VERSION: ${VERSION} # bakes into image
    environment:
      NODE_ENV: development
      APP_VERSION: ${VERSION} # runtime env
    env_file:
      - .env
    volumes:
      - ./data:/usr/share/nginx/html/data:ro
      - ./extension:/usr/share/nginx/html/extension:ro
    ports:
      - "3003:3003"
