services:
  api:
    image: zukzuk/syncnite-api:latest
    container_name: syncnite-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "3004:3004"
    volumes:
      - /volume1/docker/syncnite/data:/data
      - /volume1/docker/syncnite/extension:/extension:ro

  web:
    image: zukzuk/syncnite-web:latest
    container_name: syncnite-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "3003:3003"
    volumes:
      - /volume1/docker/syncnite/data:/usr/share/nginx/html/data:ro
      - /volume1/docker/syncnite/extension:/usr/share/nginx/html/extension:ro
